# syntax=docker/dockerfile:1

FROM golang:1.24-trixie AS build
WORKDIR /src

ADD https://raw.githubusercontent.com/andy7d0/mcp-exec/refs/heads/latest/go.mod \
     https://raw.githubusercontent.com/andy7d0/mcp-exec/refs/heads/latest/main.go \
     ./

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /mcp-executor .

# Replace this with your actual toolbox image.
FROM debian:trixie
#your-toolbox-image

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	tini curl ca-certificates git gnupg \
	python3-full python3-pip python3-venv \
	pandoc poppler-utils \
	texlive-latex-base texlive-fonts-recommended \
	texlive-xetex texlive-lang-cyrillic texlive-latex-recommended \
	build-essential \
	podman \
	ripgrep \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

ADD https://github.com/carvel-dev/ytt/releases/download/v0.55.1/ytt-linux-amd64 /usr/local/bin/

RUN NODE_VERSION="v24.19.0" \
  ARCH= && dpkgArch="$(dpkg --print-architecture)" \
  && case "${dpkgArch##*-}" in \
    amd64) ARCH='x64';; \
    arm64) ARCH='arm64';; \
    *) echo "unsupported architecture"; exit 1 ;; \
  esac \
  && curl -fsSLO --compressed "https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-$ARCH.tar.xz" \
  && curl -fsSLO --compressed "https://nodejs.org/dist/$NODE_VERSION/SHASUMS256.txt.asc" \
  && grep " node-$NODE_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt.asc | sha256sum -c - \
  && tar -xJf "node-$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
  && rm "node-$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs

#  && for key in $(curl -sL https://raw.githubusercontent.com/nodejs/docker-node/HEAD/keys/node.keys); do \
#    gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$key" || \
#    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key" ; \
#  done \
# ... download ....
#  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
# ...
#   && rm "node-$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \


RUN npm install -g corepack 
# && corepack enable yarn

RUN npm config set allow-scripts=puppeteer --location=user \
	&& npm install -g @mermaid-js/mermaid-cli

COPY --from=build /mcp-executor /usr/local/bin/mcp-executor

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/mcp-executor"]
